language: python
cache: pip
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "pypy3"
      env: TOXENV=pypy3
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: "3.8"
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: xenial
      sudo: true
#power_jobs
    - python: "3.5"
      env: TOXENV=py35
      arch: ppc64le
    - python: "3.6"
      env: TOXENV=py36
      arch: ppc64le
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true
      arch: ppc64le
    - python: "3.8"
      env: TOXENV=py38
      dist: xenial
      sudo: true
      arch: ppc64le
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: xenial
      sudo: true
      arch: ppc64le
# Disable version pypy3
jobs:
  exclude:
    - arch: ppc64le
      python: pypy3
before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - tox -e $TOXENV
after_success:
    - tox -e coverage-report
    - codecov
